[package]
name = "whale_rs"
version = "0.1.0"
edition = "2021"
authors = ["Sean McConnachie<seanjulian.mcc@gmail.com>"]

[dependencies]
crossterm = "0.27.0"
ctrlc = "3.3.1"
toml = "0.7.4"
serde = { version = "1.0.0", features = ["derive"] }
anyhow = "1.0.0"

